### ISSUE TITLE
DemoB error

### ISSUE THREAD

**Issue by gjhenley** [JuliaMPC/MAVs#59]
mavs@rosco-HP-Z440-Workstation:~$ roslaunch system demoB.launch
... logging to /home/mavs/.ros/log/28eba3b6-852c-11e8-8b08-ecb1d7429ebc/roslaunch-rosco-HP-Z440-Workstation-15535.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

roslaunch file contains multiple nodes named [/bootstrap].
Please check all <node> 'name' attributes to make sure they are unique.
Also check that $(anon id) use different ids.
The traceback for the exception was written to the log file
mavs@rosco-HP-Z440-Workstation:~$

**Comment by gjhenley** [comment]
Also get the same error for demoE.

**Comment by huckl3b3rry87** [comment]
@gjhenley thank you for the report. Working on a fix now

**Comment by huckl3b3rry87** [comment]
@gjhenley sorry about that. I just pushed a fix
https://github.com/JuliaMPC/MAVs/commit/710a7aca50002005f5549118fb0b7c0575de5591

To use the new code, change this line in your Docker file to let it know that something has changed
https://github.com/JuliaMPC/MAVs/blob/master/docker/Dockerfile#L60
for instance, instead of ``echo 4`` put ``echo 5``

Then you can rebuild the Docker with the latest code
